---
language: ruby
before_install: "gem install bundler"
script: "bundle exec rake spec"
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
branches:
  only:
    - develop
    - master
